# Generated by Django 5.1.15 on 2026-09-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_administrator', 'Super Administrator'), ('resort_manager', 'Resort Manager'), ('front_desk', 'Front Desk / Reception'), ('housekeeping', 'Housekeeping Staff'), ('accountant', 'Accountant / Finance User'), ('website_content_manager', 'Website Content Manager')], default='front_desk', max_length=32),
        ),
    ]
