# Generated by Django 5.1.15 on 2026-09-03 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_alter_user_is_active_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=16, unique=True)),
                ('name', models.CharField(default='MistnLeaf Resort', max_length=120)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('check_in_time', models.CharField(default='14:00', max_length=8)),
                ('check_out_time', models.CharField(default='11:00', max_length=8)),
                ('tax_percent', models.CharField(default='12', max_length=8)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'property settings',
                'verbose_name_plural': 'property settings',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32, unique=True)),
                ('granted', models.JSONField(blank=True, default=list)),
                ('revoked', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_permission_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'role permission override',
                'verbose_name_plural': 'role permission overrides',
            },
        ),
    ]
