# Generated by Django 5.1.15 on 2026-09-03 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_staff_ops'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=16, unique=True)),
                ('room', models.CharField(max_length=120)),
                ('issue', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('AC / HVAC', 'AC / HVAC'), ('Furniture', 'Furniture'), ('Other', 'Other')], default='Other', max_length=32)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=16)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('reported_by', models.CharField(blank=True, max_length=120)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='rooms.roomunit')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
