# Generated by Django 5.1.15 on 2026-09-02 11:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('Direct website', 'Direct website'), ('OTA / Booking.com', 'OTA / Booking.com'), ('Walk-in', 'Walk-in'), ('Travel agent', 'Travel agent')], default='Direct website', max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('Confirmed', 'Confirmed'), ('Checked-in', 'Checked In'), ('Checked-out', 'Checked Out'), ('Cancelled', 'Cancelled'), ('modified', 'Modified')], default='Pending', max_length=20),
        ),
    ]
