# Generated by Django 5.1.15 on 2026-09-02 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsContentStore',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000001'), editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CMS content',
                'verbose_name_plural': 'CMS content',
            },
        ),
    ]
