# Generated by Django 5.1.15 on 2026-09-02 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('beds', models.CharField(blank=True, max_length=120)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_label', models.CharField(blank=True, help_text='e.g. "42 m²"', max_length=32)),
                ('size_sq_ft', models.PositiveIntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('included_services', models.JSONField(blank=True, default=list)),
                ('policies', models.JSONField(blank=True, default=list)),
                ('availability_note', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('dirty', 'Dirty'), ('cleaning', 'Cleaning'), ('ready', 'Ready')], default='available', max_length=20)),
                ('housekeeping_status', models.CharField(choices=[('clean', 'Clean'), ('dirty', 'Dirty'), ('in_progress', 'In Progress'), ('inspected', 'Inspected')], default='clean', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['room_type__sort_order', 'code'],
            },
        ),
    ]
