# Generated by Django 5.1.15 on 2026-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomunit',
            name='assignee',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
